Mississippi setting
marshall-lab/TITAN pull request #139
Opened 2020-11-17 15:38 UTC by cjinspark

creates setting for black msm in mississippi

2020-11-18 15:23 UTC, s-bessey requested changes
Great work! A few edits, but it's mostly looking good. You'll need to add `partnership.sex.acquisition.MSM.versatile` before tests will run. I should have the CSV for calibration by end of day, so we can talk about getting this on Oscar and running.

2020-11-18 15:23 UTC, s-bessey commented on settings/mississippi/demographics.yml
> +        haart_adherent: 1.0
Add a newline at the end of the file

2020-11-18 15:23 UTC, s-bessey commented on settings/mississippi/model.yml
> +        receptive: 0.00425
Have to include versatile, which should be the mean of insertive and receptive

2020-11-18 15:23 UTC, s-bessey commented on settings/mississippi/model.yml
> +      scalar: 0.1088
Add a newline at the end of the file

2020-11-18 15:23 UTC, s-bessey commented on titan/params/prep.yml
> +  as_prob:
```suggestion
  target_as_prob:
```

2020-11-18 15:23 UTC, s-bessey commented on settings/mississippi/model.yml
> +  as_prob: true
```suggestion
  target_as_prob: true
```

2020-11-18 15:23 UTC, s-bessey commented on titan/features/prep.py
> +        elif params.prep.as_prob:
```suggestion
        elif params.prep.target_as_prob:
```

2020-11-18 15:23 UTC, s-bessey commented on settings/mississippi/demographics.yml
> +        base: 4.0265
Change base to 6.2 (new numbers from Will)

2020-11-19 15:59 UTC, mcmcgrath13 requested changes
🚀 Awesome!!

2020-11-19 15:59 UTC, mcmcgrath13 commented on settings/mississippi/demographics.yml
> +    MSM:
needs a `ppl` key at the `black` level as well, since 100% of the pop is black

2020-11-19 15:59 UTC, mcmcgrath13 commented on titan/params/classes.yml
>        - randint
need to add `negative_binomial` used in demographics file

2020-11-19 16:02 UTC, mcmcgrath13 commented on settings/mississippi/model.yml
> +  type: Oral
should be
```
type:
  - Oral
```
as that `prep.type` is an array param

2020-11-19 20:17 UTC, s-bessey requested changes
So close!

2020-11-19 20:17 UTC, s-bessey commented on settings/mississippi/model.yml
> +  target_model: Allcomers
```suggestion
  target_model:
    - Allcomers
```

2020-11-19 20:17 UTC, s-bessey commented on titan/params/classes.yml
> +      - weibull
Add `- negative_binomial` here as well

2020-11-19 20:17 UTC, s-bessey commented on settings/mississippi/model.yml
> +    aquisition:
```suggestion
    acquisition:
```

2020-11-19 20:17 UTC, s-bessey commented on settings/mississippi/model.yml
> +    duration:
This section needs to be moved one indent level out.

2020-11-19 20:17 UTC, s-bessey commented on settings/mississippi/demographics.yml
> +              value: 12.459
These variables don't work, waiting on Will to give correct numbers

2020-11-19 20:17 UTC, s-bessey commented on titan/features/prep.py
> +                    model.run_random.random
```suggestion
                    model.run_random.random()
```

Sorry about that!

2020-11-19 20:17 UTC, s-bessey commented on titan/features/prep.py
> +                if model.run_random <= params.prep.target:
```suggestion
                if model.run_random.random() <= params.prep.target:
```

2020-11-19 20:17 UTC, s-bessey commented on settings/mississippi/demographics.yml
> +              value: 12.459
(Yes, they're flipped)

2020-11-24 14:45 UTC, s-bessey requested changes

2020-11-24 14:45 UTC, s-bessey commented on titan/params/classes.yml
> +      - negative_bincomial
```suggestion
      - negative_binomial
```

2020-11-24 14:45 UTC, s-bessey commented on titan/features/prep.py
> +                if model.run_random() <= params.prep.target:
```suggestion
                if model.run_random.random() <= params.prep.target:
```

2020-11-24 18:34 UTC, s-bessey approved these changes
:rocket:

2020-11-24 20:56 UTC, mcmcgrath13 approved these changes

2020-11-24 21:10 UTC, merged